import { AppToaster } from "@/app/components/AppToaster";
import { CredentialProvider } from "@/app/contexts/credential-context";
import { QueryProvider } from "@/app/providers/QueryProvider";
import { StoreProvider } from "@/app/store/StoreProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} h-full antialiased`}
    >
      <body
        className={`${geistSans.className} min-h-full flex flex-col antialiased`}
      >
        <StoreProvider>
          <QueryProvider>
            <CredentialProvider>
              {children}
              <AppToaster />
            </CredentialProvider>
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
