import { CheckoutTemplateType } from "@/app/components/crm-template-editor/checkout-template-types";
import type {
  FormDesign,
  HeroDesign,
  LandingDesign,
} from "@/app/components/crm-template-editor/template-types";

export type FunnelPageDesignTemplate = {
  id: string;
  name: string;
  description: string;
  tags: string[];
  landingDesign: LandingDesign;
  heroDesign: HeroDesign;
  layoutType: string;
  formDesign: FormDesign;
  checkoutTemplate: CheckoutTemplateType;
};

export const FUNNEL_TEMPLATE_TAGS = [
  "All",
  "Popular",
  "Universal",
  "Business",
  "Minimal",
  "Dark",
  "E‑commerce",
  "Wellness",
  "Events",
  "Luxury",
] as const;

export type FunnelTemplateTag = (typeof FUNNEL_TEMPLATE_TAGS)[number];

export const FUNNEL_PAGE_DESIGN_TEMPLATES: FunnelPageDesignTemplate[] = [
  {
    id: "shopify-classic",
    name: "Shopify Classic",
    description: "Clean offer page with commerce-style checkout",
    tags: ["Popular", "E‑commerce"],
    landingDesign: "classic_offer",
    heroDesign: "edge_to_edge",
    layoutType: "centered",
    formDesign: "stacked_input_form",
    checkoutTemplate: CheckoutTemplateType.SHOPIFY,
  },
  {
    id: "wix-minimal",
    name: "Minimal Studio",
    description: "Airy layout with soft typography and Stripe checkout",
    tags: ["Popular", "Minimal"],
    landingDesign: "minimal_mono",
    heroDesign: "rounded_card",
    layoutType: "centered",
    formDesign: "underline_input_form",
    checkoutTemplate: CheckoutTemplateType.STRIPE,
  },
  {
    id: "premium-dark",
    name: "Premium Dark",
    description: "Bold dark theme with glass hero and premium checkout",
    tags: ["Popular", "Dark", "Luxury"],
    landingDesign: "midnight_glow",
    heroDesign: "glass_fade",
    layoutType: "centered",
    formDesign: "glassmorphism_form",
    checkoutTemplate: CheckoutTemplateType.PREMIUM,
  },
  {
    id: "split-editorial",
    name: "Split Editorial",
    description: "Magazine-style split layout with floating checkout",
    tags: ["Business"],
    landingDesign: "sunset_warm",
    heroDesign: "magazine_band",
    layoutType: "split",
    formDesign: "outlined_material_form",
    checkoutTemplate: CheckoutTemplateType.FLOATING,
  },
  {
    id: "crm-friendly",
    name: "CRM Friendly",
    description: "Balanced colors with built-in CRM checkout skin",
    tags: ["Popular", "E‑commerce"],
    landingDesign: "mint_frost",
    heroDesign: "split_margin",
    layoutType: "stacked",
    formDesign: "soft_shadow_form",
    checkoutTemplate: CheckoutTemplateType.CRM,
  },
  {
    id: "apple-checkout",
    name: "Apple Pay Style",
    description: "Light landing with Apple-inspired payment step",
    tags: ["E‑commerce"],
    landingDesign: "arctic_mist",
    heroDesign: "soft_frame",
    layoutType: "narrow",
    formDesign: "pill_input_form",
    checkoutTemplate: CheckoutTemplateType.APPLE,
  },
  {
    id: "forest-wellness",
    name: "Forest Wellness",
    description: "Natural greens for health, yoga, and organic brands",
    tags: ["Wellness"],
    landingDesign: "forest_fresh",
    heroDesign: "immersive_story",
    layoutType: "centered",
    formDesign: "spacious_airy_form",
    checkoutTemplate: CheckoutTemplateType.MINIMAL,
  },
  {
    id: "ocean-trust",
    name: "Ocean Trust",
    description: "Cool blues, professional, clean, and trustworthy",
    tags: ["Minimal", "E‑commerce"],
    landingDesign: "ocean_breeze",
    heroDesign: "clean_edge",
    layoutType: "centered",
    formDesign: "flat_modern_form",
    checkoutTemplate: CheckoutTemplateType.STRIPE,
  },
  {
    id: "rose-elegance",
    name: "Rose Elegance",
    description: "Blush and rose tones for beauty, events, and luxury",
    tags: ["Luxury", "Events"],
    landingDesign: "rose_elegance",
    heroDesign: "arch_curve",
    layoutType: "centered",
    formDesign: "soft_pastel_form",
    checkoutTemplate: CheckoutTemplateType.PREMIUM,
  },
  {
    id: "bold-flash",
    name: "Bold Flash Sale",
    description: "High-contrast yellow on black, loud, urgent campaigns",
    tags: ["Events", "E‑commerce"],
    landingDesign: "bold_contrast",
    heroDesign: "wide_banner",
    layoutType: "wide",
    formDesign: "high_contrast_form",
    checkoutTemplate: CheckoutTemplateType.DARK,
  },
  {
    id: "golden-membership",
    name: "Golden Membership",
    description: "Gold on charcoal, premium clubs and memberships",
    tags: ["Luxury", "Business"],
    landingDesign: "golden_hour",
    heroDesign: "premium_inset",
    layoutType: "centered",
    formDesign: "elevated_card_form",
    checkoutTemplate: CheckoutTemplateType.PREMIUM,
  },
  {
    id: "cream-hospitality",
    name: "Cream Hospitality",
    description: "Warm paper tones, calm, readable, business-ready",
    tags: ["Business", "Popular"],
    landingDesign: "soft_cream",
    heroDesign: "tall_focus",
    layoutType: "stacked",
    formDesign: "light_panel_form",
    checkoutTemplate: CheckoutTemplateType.SHOPIFY,
  },
  {
    id: "plum-spa",
    name: "Plum Spa",
    description: "Deep purple luxury, spas, wine bars, and boutiques",
    tags: ["Luxury", "Wellness"],
    landingDesign: "plum_luxe",
    heroDesign: "floating_hero",
    layoutType: "centered",
    formDesign: "neumorphism_form",
    checkoutTemplate: CheckoutTemplateType.FLOATING,
  },
  {
    id: "coral-fun",
    name: "Coral Pop",
    description: "Bright coral and pink, fun promos and family brands",
    tags: ["Events", "Business"],
    landingDesign: "coral_pop",
    heroDesign: "product_square",
    layoutType: "centered",
    formDesign: "rounded_corner_form",
    checkoutTemplate: CheckoutTemplateType.CRM,
  },
  {
    id: "arctic-saas",
    name: "Arctic SaaS",
    description: "Cool gray minimal, tech, SaaS, and pro services",
    tags: ["Minimal", "E‑commerce"],
    landingDesign: "arctic_mist",
    heroDesign: "split_margin",
    layoutType: "narrow",
    formDesign: "desktop_business_form",
    checkoutTemplate: CheckoutTemplateType.STRIPE,
  },
  {
    id: "electric-nightlife",
    name: "Electric Nightlife",
    description: "Neon on violet, concerts, clubs, and live events",
    tags: ["Events", "Dark"],
    landingDesign: "electric_pulse",
    heroDesign: "immersive_story",
    layoutType: "wide",
    formDesign: "dark_mode_form",
    checkoutTemplate: CheckoutTemplateType.DARK,
  },
  {
    id: "sage-yoga",
    name: "Sage Calm",
    description: "Muted sage green, yoga, meditation, and calm brands",
    tags: ["Wellness"],
    landingDesign: "sage_calm",
    heroDesign: "soft_frame",
    layoutType: "centered",
    formDesign: "transparent_form",
    checkoutTemplate: CheckoutTemplateType.MINIMAL,
  },
  {
    id: "wine-dining",
    name: "Wine Velvet",
    description: "Rich burgundy, fine dining and wine clubs",
    tags: ["Business", "Luxury"],
    landingDesign: "wine_velvet",
    heroDesign: "wide_banner",
    layoutType: "split",
    formDesign: "bold_label_form",
    checkoutTemplate: CheckoutTemplateType.PREMIUM,
  },
  {
    id: "candy-bakery",
    name: "Candy Shop",
    description: "Playful fuchsia, bakeries, treats, and family brands",
    tags: ["Business", "Events"],
    landingDesign: "candy_shop",
    heroDesign: "product_square",
    layoutType: "centered",
    formDesign: "mobile_app_form",
    checkoutTemplate: CheckoutTemplateType.APPLE,
  },
  {
    id: "coastal-resort",
    name: "Coastal Resort",
    description: "Teal and sand, beach clubs, resorts, and travel",
    tags: ["Business", "Events"],
    landingDesign: "coastal_sand",
    heroDesign: "edge_to_edge",
    layoutType: "wide",
    formDesign: "floating_label_form",
    checkoutTemplate: CheckoutTemplateType.FLOATING,
  },
  {
    id: "graphite-b2b",
    name: "Graphite Pro",
    description: "Slate blue dark, finance, consulting, and B2B",
    tags: ["Dark", "E‑commerce"],
    landingDesign: "graphite_pro",
    heroDesign: "premium_inset",
    layoutType: "narrow",
    formDesign: "sectioned_form",
    checkoutTemplate: CheckoutTemplateType.SPLIT,
  },
  {
    id: "berry-retail",
    name: "Berry Burst",
    description: "Bold berry red, retail drops and limited releases",
    tags: ["E‑commerce", "Events"],
    landingDesign: "berry_burst",
    heroDesign: "wide_banner",
    layoutType: "centered",
    formDesign: "compact_dense_form",
    checkoutTemplate: CheckoutTemplateType.SHOPIFY,
  },
  {
    id: "evergreen-outdoor",
    name: "Evergreen Outdoor",
    description: "Deep forest green, outdoor, eco, and adventure",
    tags: ["Wellness", "Events"],
    landingDesign: "evergreen_night",
    heroDesign: "immersive_story",
    layoutType: "split",
    formDesign: "outlined_material_form",
    checkoutTemplate: CheckoutTemplateType.MINIMAL,
  },
  {
    id: "minimal-checkout",
    name: "Pure Minimal",
    description: "White space hero with the lightest checkout skin",
    tags: ["Minimal", "Popular"],
    landingDesign: "minimal_mono",
    heroDesign: "clean_edge",
    layoutType: "centered",
    formDesign: "thin_line_form",
    checkoutTemplate: CheckoutTemplateType.MINIMAL,
  },
  {
    id: "shop-split-dark",
    name: "Split Dark Checkout",
    description: "Dark landing with split-column checkout layout",
    tags: ["Dark", "E‑commerce"],
    landingDesign: "graphite_pro",
    heroDesign: "glass_fade",
    layoutType: "split",
    formDesign: "dark_mode_form",
    checkoutTemplate: CheckoutTemplateType.SPLIT,
  },
  {
    id: "universal-clean",
    name: "Universal Clean",
    description:
      "Neutral mono palette with adaptive inset hero — any image ratio fits without cropping",
    tags: ["Popular", "Minimal", "Universal"],
    landingDesign: "minimal_mono",
    heroDesign: "adaptive_inset",
    layoutType: "centered",
    formDesign: "thin_line_form",
    checkoutTemplate: CheckoutTemplateType.MINIMAL,
  },
  {
    id: "universal-studio",
    name: "Universal Studio",
    description:
      "Cool gray studio look; square adaptive frame for logos and product shots",
    tags: ["Minimal", "Business", "Universal"],
    landingDesign: "arctic_mist",
    heroDesign: "adaptive_square",
    layoutType: "centered",
    formDesign: "underline_input_form",
    checkoutTemplate: CheckoutTemplateType.STRIPE,
  },
  {
    id: "universal-wide",
    name: "Universal Wide",
    description:
      "Warm cream page with wide letterbox hero for landscape and panoramic photos",
    tags: ["Business", "Universal"],
    landingDesign: "soft_cream",
    heroDesign: "adaptive_wide",
    layoutType: "wide",
    formDesign: "light_panel_form",
    checkoutTemplate: CheckoutTemplateType.SHOPIFY,
  },
  {
    id: "universal-portrait",
    name: "Universal Portrait",
    description:
      "Soft blue trust tones with tall adaptive frame for vertical photography",
    tags: ["Popular", "Universal"],
    landingDesign: "ocean_breeze",
    heroDesign: "adaptive_portrait",
    layoutType: "centered",
    formDesign: "flat_modern_form",
    checkoutTemplate: CheckoutTemplateType.STRIPE,
  },
  {
    id: "universal-float",
    name: "Universal Float",
    description:
      "Mint frost palette with floating adaptive card — blends busy or mixed-ratio images",
    tags: ["Minimal", "Wellness", "Universal"],
    landingDesign: "mint_frost",
    heroDesign: "adaptive_floating",
    layoutType: "centered",
    formDesign: "spacious_airy_form",
    checkoutTemplate: CheckoutTemplateType.FLOATING,
  },
  {
    id: "universal-frame",
    name: "Universal Frame",
    description:
      "Editorial bordered hero with neutral backdrop; safe default for any upload",
    tags: ["Business", "Popular", "Universal"],
    landingDesign: "soft_cream",
    heroDesign: "adaptive_frame",
    layoutType: "stacked",
    formDesign: "minimal_border_form",
    checkoutTemplate: CheckoutTemplateType.CRM,
  },
  {
    id: "universal-classic",
    name: "Universal Classic",
    description:
      "Soft lavender offer page with adaptive inset — versatile for brand photos",
    tags: ["Popular", "E‑commerce", "Universal"],
    landingDesign: "classic_offer",
    heroDesign: "adaptive_inset",
    layoutType: "centered",
    formDesign: "stacked_input_form",
    checkoutTemplate: CheckoutTemplateType.SHOPIFY,
  },
  {
    id: "universal-sage",
    name: "Universal Sage",
    description:
      "Calm sage wellness palette with portrait adaptive hero for people and products",
    tags: ["Wellness", "Universal"],
    landingDesign: "sage_calm",
    heroDesign: "adaptive_portrait",
    layoutType: "centered",
    formDesign: "transparent_form",
    checkoutTemplate: CheckoutTemplateType.MINIMAL,
  },
  {
    id: "universal-neutral",
    name: "Universal Neutral",
    description:
      "Arctic gray minimal with adaptive square — works with logos, menus, and interiors",
    tags: ["Minimal", "Business", "Universal"],
    landingDesign: "arctic_mist",
    heroDesign: "adaptive_square",
    layoutType: "narrow",
    formDesign: "desktop_business_form",
    checkoutTemplate: CheckoutTemplateType.STRIPE,
  },
  {
    id: "universal-panorama",
    name: "Universal Panorama",
    description:
      "Light minimal page with wide adaptive band for storefronts and venue shots",
    tags: ["Business", "Events", "Universal"],
    landingDesign: "minimal_mono",
    heroDesign: "adaptive_wide",
    layoutType: "wide",
    formDesign: "compact_dense_form",
    checkoutTemplate: CheckoutTemplateType.MINIMAL,
  },
];

export function funnelDesignTemplatesForTag(tag: FunnelTemplateTag): FunnelPageDesignTemplate[] {
  if (tag === "All") return FUNNEL_PAGE_DESIGN_TEMPLATES;
  return FUNNEL_PAGE_DESIGN_TEMPLATES.filter((t) => t.tags.includes(tag));
}

export const FUNNEL_PAGE_TEMPLATES = FUNNEL_PAGE_DESIGN_TEMPLATES;
export type FunnelPageTemplate = FunnelPageDesignTemplate;
export const funnelTemplatesForTag = funnelDesignTemplatesForTag;
